#!/usr/bin/env bash
### This script can be used with SSH_ASKPASS to push keycloak automatically to your browser.  Add a shell function such as:
### kssh() { SSH_ASKPASS=~/.local/bin/keycloak-askpass SSH_ASKPASS_REQUIRE=force ssh "$@"; }
###
prompt="$1"
url=$(grep -oE 'https://[^ ]+' <<<"$prompt")

if [[ -n $url ]]; then
    case $(uname -s) in 
      "Linux" )
        # for standard linux desktop
         command -v xdg-open >/dev/null 2>&1 && xdg-open "$url" >/dev/null 2>&1 &
         # for WSL and possibly VSCode (requires `sudo apt install wslu`)
         command -v wslview >/dev/null 2>&1 && wslview "$url" >/dev/null 2>&1 &
      ;;
      "Darwin" )
         open "$url" >/dev/null 2>&1 &
      ;;
    * )
      echo "This can only run from Linux (with default desktop setup), MacOS, or WSL (with wslu installed)"
         exit 1
    esac
    printf 'Keycloak login can be completed in the browser, then press ENTER '  >/dev/tty
    read -r </dev/tty
    echo ""          # the empty answer is the "press ENTER"
else
    echo "Not sure this is a keycloak auth, bye"
fi
